name: Deploy to Server

on:
  push:
    branches:
      - main  # o el nombre de tu rama principal

jobs:
  deploy:
    runs-on: centos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into server and run deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /ruta/a/tu/proyecto
            ./deploy.sh
